#include "algorithm/algorithm_base.hpp"
#include "algorithm/shading.hpp"
#include "algorithm/flare.hpp"
#include "algorithm/blemish.hpp"
#include "algorithm/blemishPixel.hpp"
#include "algorithm/blemishStat.hpp"